#!/usr/bin/env python3
"""
Simple Agent Example for API Conformance Gym

This example demonstrates how to create a basic RL agent that interacts with
the API Conformance Gym environment. The agent uses a simple rule-based approach
to iteratively improve OpenAPI schemas based on validation feedback.

Usage:
    python examples/simple_agent.py

Requirements:
    - API Conformance Gym environment running on localhost:8000
    - Or Docker image available for automatic startup
"""

import asyncio
import json
import random
from typing import Dict, Any

try:
    from api_conformance_gym import APIEnvClient, APIAction
except ImportError:
    import sys
    import os
    sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    from client import APIEnvClient
    from models import APIAction


class SimpleAPIAgent:
    """
    A simple rule-based agent for API design.
    
    This agent demonstrates basic strategies for improving OpenAPI schemas:
    - Start with a minimal valid schema
    - Add missing required fields based on validation errors
    - Implement basic security schemes
    - Add documentation and error responses
    """
    
    def __init__(self):
        self.base_schema = {
            "openapi": "3.0.0",
            "info": {
                "title": "Generated API",
                "version": "1.0.0",
                "description": "API generated by simple agent"
            },
            "servers": [{"url": "https://api.example.com/v1"}],
            "paths": {},
            "components": {
                "securitySchemes": {
                    "bearerAuth": {
                        "type": "http",
                        "scheme": "bearer",
                        "bearerFormat": "JWT"
                    }
                }
            },
            "security": [{"bearerAuth": []}]
        }
    
    def analyze_business_requirement(self, requirement: str) -> Dict[str, Any]:
        """Analyze business requirement to determine API structure."""
        requirement_lower = requirement.lower()
        
        # Simple keyword-based analysis
        endpoints = {}
        
        # Common patterns
        if "library" in requirement_lower or "book" in requirement_lower:
            endpoints.update({
                "/books": ["get", "post"],
                "/books/{id}": ["get", "put", "delete"],
                "/users/{id}/borrowed": ["get"]
            })
        elif "ecommerce" in requirement_lower or "shop" in requirement_lower:
            endpoints.update({
                "/products": ["get", "post"],
                "/products/{id}": ["get", "put", "delete"],
                "/cart": ["get", "post"],
                "/orders": ["get", "post"],
                "/orders/{id}": ["get"]
            })
        elif "auth" in requirement_lower or "user" in requirement_lower:
            endpoints.update({
                "/auth/register": ["post"],
                "/auth/login": ["post"],
                "/auth/logout": ["post"],
                "/users/profile": ["get", "put"]
            })
        elif "data" in requirement_lower or "analytics" in requirement_lower:
            endpoints.update({
                "/datasets": ["get", "post"],
                "/datasets/{id}": ["get", "put", "delete"],
                "/queries": ["post"],
                "/reports": ["get", "post"]
            })
        else:
            # Generic CRUD endpoints
            endpoints.update({
                "/items": ["get", "post"],
                "/items/{id}": ["get", "put", "delete"]
            })
        
        return {"endpoints": endpoints}
    
    def create_path_item(self, path: str, methods: list) -> Dict[str, Any]:
        """Create a path item with operations for the given methods."""
        path_item = {}
        
        for method in methods:
            operation = {
                "summary": f"{method.upper()} {path}",
                "description": f"Perform {method.upper()} operation on {path}",
                "responses": {
                    "200": {"description": "Success"},
                    "400": {"description": "Bad Request"},
                    "401": {"description": "Unauthorized"},
                    "404": {"description": "Not Found"},
                    "500": {"description": "Internal Server Error"}
                }
            }
            
            # Add request body for POST, PUT, PATCH
            if method in ["post", "put", "patch"]:
                operation["requestBody"] = {
                    "required": True,
                    "content": {
                        "application/json": {
                            "schema": {"type": "object"}
                        }
                    }
                }
            
            # Add parameters for path variables
            if "{" in path:
                param_name = path.split("{")[1].split("}")[0]
                operation["parameters"] = [{
                    "name": param_name,
                    "in": "path",
                    "required": True,
                    "schema": {"type": "string"},
                    "description": f"The {param_name} identifier"
                }]
            
            path_item[method] = operation
        
        return path_item
    
    def improve_schema_based_on_errors(self, schema: Dict[str, Any], errors: list) -> Dict[str, Any]:
        """Improve schema based on validation errors."""
        improved_schema = schema.copy()
        
        for error in errors:
            error_type = error.error_type
            path = error.path
            
            if error_type == "missing_required_field":
                if "openapi" in error.message and "openapi" not in improved_schema:
                    improved_schema["openapi"] = "3.0.0"
                elif "info" in error.message and "info" not in improved_schema:
                    improved_schema["info"] = {"title": "API", "version": "1.0.0"}
                elif "paths" in error.message and "paths" not in improved_schema:
                    improved_schema["paths"] = {}
            
            elif error_type == "missing_auth_schemes":
                if "components" not in improved_schema:
                    improved_schema["components"] = {}
                if "securitySchemes" not in improved_schema["components"]:
                    improved_schema["components"]["securitySchemes"] = {
                        "bearerAuth": {"type": "http", "scheme": "bearer"}
                    }
                if "security" not in improved_schema:
                    improved_schema["security"] = [{"bearerAuth": []}]
            
            elif error_type == "incomplete_documentation":
                # Add more detailed descriptions
                if "info" in improved_schema and "description" not in improved_schema["info"]:
                    improved_schema["info"]["description"] = "API with comprehensive documentation"
            
            elif error_type == "missing_versioning":
                if "info" in improved_schema:
                    improved_schema["info"]["version"] = "1.0.0"
        
        return improved_schema
    
    async def run_episode(self, env: APIEnvClient) -> Dict[str, Any]:
        """Run a complete episode with the environment."""
        print("🚀 Starting new episode...")
        
        # Reset environment
        result = await env.reset()
        state = result.observation if hasattr(result, 'observation') else result
        
        print(f"📋 Business Requirement:")
        print(f"   {state.business_requirement}")
        print()
        
        # Analyze requirement
        analysis = self.analyze_business_requirement(state.business_requirement)
        
        # Start with base schema
        current_schema = self.base_schema.copy()
        
        # Add endpoints based on analysis
        for path, methods in analysis["endpoints"].items():
            current_schema["paths"][path] = self.create_path_item(path, methods)
        
        episode_rewards = []
        episode_feedback = []
        
        for iteration in range(1, 11):  # Max 10 iterations
            print(f"🔄 Iteration {iteration}")
            
            # Create action
            action = APIAction(
                schema_json=json.dumps(current_schema, indent=2),
                iteration=iteration,
                metadata={"agent": "simple_rule_based"}
            )
            
            # Execute step
            result = await env.step(action)
            observation = result.observation
            reward = result.reward or 0.0
            done = result.done
            
            episode_rewards.append(reward)
            episode_feedback.append(observation.schema_feedback)
            
            print(f"   💰 Reward: {reward:.3f}")
            print(f"   🎯 Validity Score: {observation.validity_score:.3f}")
            print(f"   ⭐ Best Practices Score: {observation.best_practices_score:.3f}")
            print(f"   ❌ Error Count: {observation.error_count}")
            print(f"   💬 Feedback: {observation.schema_feedback}")
            
            if observation.error_count > 0:
                print(f"   🔧 Top errors:")
                for i, error in enumerate(observation.validation_errors[:3]):
                    print(f"      {i+1}. {error.error_type}: {error.message}")
            
            print()
            
            if done:
                print("✅ Episode completed!")
                break
            
            # Improve schema based on errors
            if observation.validation_errors:
                current_schema = self.improve_schema_based_on_errors(
                    current_schema, observation.validation_errors
                )
        
        return {
            "total_reward": sum(episode_rewards),
            "average_reward": sum(episode_rewards) / len(episode_rewards) if episode_rewards else 0,
            "final_validity_score": observation.validity_score,
            "final_best_practices_score": observation.best_practices_score,
            "final_error_count": observation.error_count,
            "iterations": len(episode_rewards),
            "episode_rewards": episode_rewards,
            "episode_feedback": episode_feedback
        }


async def main():
    """Main function to run the simple agent."""
    print("🏗️  API Conformance Gym - Simple Agent Example")
    print("=" * 50)
    
    # Try to connect to environment
    try:
        # First try connecting to existing server
        env = APIEnvClient(base_url="http://localhost:8000")
        print("🔗 Connected to existing server at localhost:8000")
    except Exception:
        print("⚠️  Could not connect to localhost:8000")
        print("   Please start the environment server first:")
        print("   uvicorn server.app:app --host 0.0.0.0 --port 8000")
        return
    
    agent = SimpleAPIAgent()
    
    try:
        # Run multiple episodes
        num_episodes = 3
        all_results = []
        
        for episode in range(1, num_episodes + 1):
            print(f"\n🎮 Episode {episode}/{num_episodes}")
            print("-" * 30)
            
            result = await agent.run_episode(env)
            all_results.append(result)
            
            print(f"📊 Episode {episode} Summary:")
            print(f"   Total Reward: {result['total_reward']:.3f}")
            print(f"   Average Reward: {result['average_reward']:.3f}")
            print(f"   Final Validity: {result['final_validity_score']:.3f}")
            print(f"   Final Best Practices: {result['final_best_practices_score']:.3f}")
            print(f"   Final Errors: {result['final_error_count']}")
            print(f"   Iterations: {result['iterations']}")
        
        # Overall statistics
        print(f"\n📈 Overall Performance ({num_episodes} episodes):")
        print("-" * 40)
        avg_total_reward = sum(r['total_reward'] for r in all_results) / len(all_results)
        avg_validity = sum(r['final_validity_score'] for r in all_results) / len(all_results)
        avg_best_practices = sum(r['final_best_practices_score'] for r in all_results) / len(all_results)
        avg_errors = sum(r['final_error_count'] for r in all_results) / len(all_results)
        
        print(f"Average Total Reward: {avg_total_reward:.3f}")
        print(f"Average Final Validity: {avg_validity:.3f}")
        print(f"Average Final Best Practices: {avg_best_practices:.3f}")
        print(f"Average Final Errors: {avg_errors:.1f}")
        
    except KeyboardInterrupt:
        print("\n⏹️  Interrupted by user")
    except Exception as e:
        print(f"\n❌ Error during execution: {e}")
    finally:
        await env.close()
        print("🔌 Environment connection closed")


if __name__ == "__main__":
    asyncio.run(main())